-- MySQL Script generated by MySQL Workbench
-- Mon Apr 30 13:11:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tcc_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tcc_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcc_bd` DEFAULT CHARACTER SET utf8 ;
USE `tcc_bd` ;

-- -----------------------------------------------------
-- Table `tcc_bd`.`Instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`Instituicao` (
  `idInstituicao` INT NOT NULL AUTO_INCREMENT,
  `nomeInstituicao` VARCHAR(60) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idInstituicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`Administrativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`Administrativo` (
  `idAdministrativo` INT NOT NULL AUTO_INCREMENT,
  `status` INT NOT NULL,
  `permissao` INT NOT NULL,
  PRIMARY KEY (`idAdministrativo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`Comum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`Comum` (
  `idComum` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idComum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL,
  `senha` CHAR(32) NOT NULL,
  `Administrativo_idAdministrativo` INT NOT NULL,
  `Comum_idComum` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Administrativo1_idx` (`Administrativo_idAdministrativo` ASC),
  INDEX `fk_Usuario_Comum1_idx` (`Comum_idComum` ASC),
  CONSTRAINT `fk_Usuario_Administrativo1`
    FOREIGN KEY (`Administrativo_idAdministrativo`)
    REFERENCES `tcc_bd`.`Administrativo` (`idAdministrativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Comum1`
    FOREIGN KEY (`Comum_idComum`)
    REFERENCES `tcc_bd`.`Comum` (`idComum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`InstituicaoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`InstituicaoUsuario` (
  `Instituicao_idInstituicao` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  INDEX `fk_Instituicao_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Instituicao_has_Usuario_Instituicao_idx` (`Instituicao_idInstituicao` ASC),
  PRIMARY KEY (`Instituicao_idInstituicao`, `Usuario_idUsuario`),
  CONSTRAINT `fk_Instituicao_has_Usuario_Instituicao`
    FOREIGN KEY (`Instituicao_idInstituicao`)
    REFERENCES `tcc_bd`.`Instituicao` (`idInstituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Instituicao_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `tcc_bd`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`Turma` (
  `idTurma` INT NOT NULL AUTO_INCREMENT,
  `modulo` INT NOT NULL,
  `periodo` INT NOT NULL,
  `cod_turma` INT NOT NULL,
  PRIMARY KEY (`idTurma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`TurmaComum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`TurmaComum` (
  `Turma_idTurma` INT NOT NULL,
  `Comum_idComum` INT NOT NULL,
  PRIMARY KEY (`Turma_idTurma`, `Comum_idComum`),
  INDEX `fk_Turma_has_Comum_Comum1_idx` (`Comum_idComum` ASC),
  INDEX `fk_Turma_has_Comum_Turma1_idx` (`Turma_idTurma` ASC),
  CONSTRAINT `fk_Turma_has_Comum_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `tcc_bd`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_has_Comum_Comum1`
    FOREIGN KEY (`Comum_idComum`)
    REFERENCES `tcc_bd`.`Comum` (`idComum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`Materia` (
  `idMateria` INT NOT NULL AUTO_INCREMENT,
  `materia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`TurmaMateria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`TurmaMateria` (
  `Materia_idMateria` INT NOT NULL,
  `Turma_idTurma` INT NOT NULL,
  PRIMARY KEY (`Materia_idMateria`, `Turma_idTurma`),
  INDEX `fk_Materia_has_Turma_Turma1_idx` (`Turma_idTurma` ASC),
  INDEX `fk_Materia_has_Turma_Materia1_idx` (`Materia_idMateria` ASC),
  CONSTRAINT `fk_Materia_has_Turma_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `tcc_bd`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materia_has_Turma_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `tcc_bd`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`HorariosDisponiveisProfessores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`HorariosDisponiveisProfessores` (
  `idHorariosDisponiveisProfessores` INT NOT NULL AUTO_INCREMENT,
  `horarioInicial` DATE NOT NULL,
  `horarioFinal` DATE NOT NULL,
  PRIMARY KEY (`idHorariosDisponiveisProfessores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`Professor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `nomeProfessor` VARCHAR(45) NOT NULL,
  `HorariosDisponiveisProfessores_idHorariosDisponiveisProfessores` INT NOT NULL,
  PRIMARY KEY (`idProfessor`),
  INDEX `fk_Professor_HorariosDisponiveisProfessores1_idx` (`HorariosDisponiveisProfessores_idHorariosDisponiveisProfessores` ASC),
  CONSTRAINT `fk_Professor_HorariosDisponiveisProfessores1`
    FOREIGN KEY (`HorariosDisponiveisProfessores_idHorariosDisponiveisProfessores`)
    REFERENCES `tcc_bd`.`HorariosDisponiveisProfessores` (`idHorariosDisponiveisProfessores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`Aula` (
  `idAula` INT NOT NULL AUTO_INCREMENT,
  `nmrPosicao` INT NULL,
  `Materia_idMateria` INT NOT NULL,
  `Professor_idProfessor` INT NOT NULL,
  PRIMARY KEY (`idAula`),
  INDEX `fk_Aula_Materia1_idx` (`Materia_idMateria` ASC),
  INDEX `fk_Aula_Professor1_idx` (`Professor_idProfessor` ASC),
  CONSTRAINT `fk_Aula_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `tcc_bd`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aula_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `tcc_bd`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`HorarioDiario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`HorarioDiario` (
  `idHorarioDiario` INT NOT NULL AUTO_INCREMENT,
  `horarioInicial` DATE NOT NULL,
  `horarioFinal` DATE NOT NULL,
  PRIMARY KEY (`idHorarioDiario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`HorariosDisponiveisInstituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`HorariosDisponiveisInstituicao` (
  `idHorariosDisponiveisInstituicao` INT NOT NULL AUTO_INCREMENT,
  `tipoPeriodo` INT NOT NULL,
  `horarioInicial` DATE NOT NULL,
  `horarioFinal` DATE NOT NULL,
  PRIMARY KEY (`idHorariosDisponiveisInstituicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`HorarioDiarioHorariosDisponiveisInstituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`HorarioDiarioHorariosDisponiveisInstituicao` (
  `HorarioDiario_idHorarioDiario` INT NOT NULL,
  `HorariosDisponiveisInstituicao_idHorariosDisponiveisInstituicao` INT NOT NULL,
  PRIMARY KEY (`HorarioDiario_idHorarioDiario`, `HorariosDisponiveisInstituicao_idHorariosDisponiveisInstituicao`),
  INDEX `fk_HorarioDiario_has_HorariosDisponiveisInstituicao_Horario_idx` (`HorariosDisponiveisInstituicao_idHorariosDisponiveisInstituicao` ASC),
  INDEX `fk_HorarioDiario_has_HorariosDisponiveisInstituicao_Horario_idx1` (`HorarioDiario_idHorarioDiario` ASC),
  CONSTRAINT `fk_HorarioDiario_has_HorariosDisponiveisInstituicao_HorarioDi1`
    FOREIGN KEY (`HorarioDiario_idHorarioDiario`)
    REFERENCES `tcc_bd`.`HorarioDiario` (`idHorarioDiario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HorarioDiario_has_HorariosDisponiveisInstituicao_HorariosD1`
    FOREIGN KEY (`HorariosDisponiveisInstituicao_idHorariosDisponiveisInstituicao`)
    REFERENCES `tcc_bd`.`HorariosDisponiveisInstituicao` (`idHorariosDisponiveisInstituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`Cronograma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`Cronograma` (
  `idCronograma` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idCronograma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`CronogramaDia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`CronogramaDia` (
  `idCronogramaDia` INT NOT NULL AUTO_INCREMENT,
  `nmr_aula` INT NOT NULL,
  `Cronograma_idCronograma` INT NOT NULL,
  PRIMARY KEY (`idCronogramaDia`, `Cronograma_idCronograma`),
  INDEX `fk_CronogramaDia_Cronograma1_idx` (`Cronograma_idCronograma` ASC),
  CONSTRAINT `fk_CronogramaDia_Cronograma1`
    FOREIGN KEY (`Cronograma_idCronograma`)
    REFERENCES `tcc_bd`.`Cronograma` (`idCronograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`AulaCronogramaDia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`AulaCronogramaDia` (
  `Aula_idAula` INT NOT NULL,
  `CronogramaDia_idCronogramaDia` INT NOT NULL,
  PRIMARY KEY (`Aula_idAula`, `CronogramaDia_idCronogramaDia`),
  INDEX `fk_Aula_has_CronogramaDia_CronogramaDia1_idx` (`CronogramaDia_idCronogramaDia` ASC),
  INDEX `fk_Aula_has_CronogramaDia_Aula1_idx` (`Aula_idAula` ASC),
  CONSTRAINT `fk_Aula_has_CronogramaDia_Aula1`
    FOREIGN KEY (`Aula_idAula`)
    REFERENCES `tcc_bd`.`Aula` (`idAula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aula_has_CronogramaDia_CronogramaDia1`
    FOREIGN KEY (`CronogramaDia_idCronogramaDia`)
    REFERENCES `tcc_bd`.`CronogramaDia` (`idCronogramaDia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc_bd`.`CronogramaDiaHorariosDisponiveisInstituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc_bd`.`CronogramaDiaHorariosDisponiveisInstituicao` (
  `CronogramaDia_idCronogramaDia` INT NOT NULL,
  `HorariosDisponiveisInstituicao_idHorariosDisponiveisInstituicao` INT NOT NULL,
  PRIMARY KEY (`CronogramaDia_idCronogramaDia`, `HorariosDisponiveisInstituicao_idHorariosDisponiveisInstituicao`),
  INDEX `fk_CronogramaDia_has_HorariosDisponiveisInstituicao_Horario_idx` (`HorariosDisponiveisInstituicao_idHorariosDisponiveisInstituicao` ASC),
  INDEX `fk_CronogramaDia_has_HorariosDisponiveisInstituicao_Cronogr_idx` (`CronogramaDia_idCronogramaDia` ASC),
  CONSTRAINT `fk_CronogramaDia_has_HorariosDisponiveisInstituicao_Cronogram1`
    FOREIGN KEY (`CronogramaDia_idCronogramaDia`)
    REFERENCES `tcc_bd`.`CronogramaDia` (`idCronogramaDia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CronogramaDia_has_HorariosDisponiveisInstituicao_HorariosD1`
    FOREIGN KEY (`HorariosDisponiveisInstituicao_idHorariosDisponiveisInstituicao`)
    REFERENCES `tcc_bd`.`HorariosDisponiveisInstituicao` (`idHorariosDisponiveisInstituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
